stages:
  - init
  - build
  - deploy

install-dependencies:
  stage: init
  script:
  - npm-install-missing
  - bundler install
  cache:
    paths:
    - node_modules/
  artifacts:
    paths:
    - node_modules/

build:
  stage: build
  script:
  - cd src && jekyll build
  - cd ../ && grunt --force
  artifacts:
    paths:
    - node_modules/
    - src/_site/

deploy-to-live:
  stage: deploy
  only:
  - release
  script:
  - grunt deploy

deploy-to-test:
  stage: deploy
  only:
  - master
  script:
  - grunt deploy:test