stages:
  - init
  - build
  - deploy

install-dependencies:
  stage: init
  script:
  - echo "$CI_BUILD_NAME"
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - node_modules/

build:
  stage: build
  script:
  - cd src && jekyll build
  - cd ../ && grunt --force
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - node_modules/

deploy-to-live:
  stage: deploy
  only:
  - release
  script:
  - grunt deploy
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - node_modules/
  artifacts:
    paths:
    - src/_site/

deploy-to-test:
  stage: deploy
  only:
  - master
  script:
  - grunt deploy:test
  cache:
    key: "$CI_BUILD_NAME"
    paths:
    - node_modules/
  artifacts:
    paths:
    - src/_site/