before_script:
  - npm install
  - bundler install

stages:
  - build
  - deploy

cache:
  paths:
  - node_modules/

build:
  stage: build
  script:
  - cd src && jekyll build
  - cd ../ && grunt --force

deploy-to-live:
  stage: deploy
  only:
  - release
  script:
  - grunt deploy
  artifacts:
    paths:
    - src/_site/

deploy-to-test:
  stage: deploy
  only:
  - master
  script:
  - grunt deploy:test
  artifacts:
    paths:
    - src/_site/