stages:
  - init
  - build
  - deploy

cache:
  key: "$CI_BUILD_NAME"
  paths:
  - node_modules/

install-dependencies:
  stage: init
  script:
  - npm-install-missing
  - bundler install

build:
  stage: build
  script:
  - cd src && jekyll build
  - cd ../ && grunt --force

deploy-to-live:
  stage: deploy
  only:
  - release
  script:
  - grunt deploy
  artifacts:
    paths:
    - src/_site/

deploy-to-test:
  stage: deploy
  only:
  - master
  script:
  - grunt deploy:test
  artifacts:
    paths:
    - src/_site/