stages:
  - install
  - build
  - deploy

cache:
  paths:
  - node_modules/

install-dependencies:
  stage: install
  script:
  - npm-install-missing
  - bundler install

build:
  stage: build
  script:
  - cd src && jekyll build
  - cd ../ && grunt --force
  artifacts:
    paths:
    - src/_site/

deploy-to-live:
  stage: deploy
  only:
  - release
  script:
  - grunt deploy

deploy-to-test:
  stage: deploy
  only:
  - master
  script:
  - grunt deploy:test