version: "3.8"

x-update-config: &update-config
  update_config:
    parallelism: 1
    failure_action: rollback
    order: start-first
    monitor: 120s
    delay: 0s

services:
  nginx:
    image: $IMAGE_RELEASE/nginx:$TAG
    networks:
      - kris-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.referrerPolicy=strict-origin-when-cross-origin"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.stsSeconds=31536000"
        - "traefik.http.routers.${STACK_NAME}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}-http.middlewares=enforce-https@file,${STACK_NAME}-security"
        - "traefik.http.routers.${STACK_NAME}-http.rule=Host(`${HOST_NAME}`, `www.${HOST_NAME}`)"
        - "traefik.http.routers.${STACK_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-https.middlewares=${STACK_NAME}-security"
        - "traefik.http.routers.${STACK_NAME}-https.rule=Host(`${HOST_NAME}`, `www.${HOST_NAME}`)"
        - "traefik.http.routers.${STACK_NAME}-https.tls.certresolver=tlsChallenge"
        - "traefik.http.routers.${STACK_NAME}-https.tls.options=modern@file"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
        - "traefik.http.middlewares.${STACK_NAME}-www-redirect.redirectregex.regex=^https://www.${HOST_NAME}/(.*)"
        - "traefik.http.middlewares.${STACK_NAME}-www-redirect.redirectregex.replacement=https://${HOST_NAME}/$${1}"
        - "traefik.http.middlewares.${STACK_NAME}-www-redirect.redirectregex.permanent=true"
        - "traefik.http.routers.${STACK_NAME}-https.middlewares=${STACK_NAME}-www-redirect"
      <<: *update-config
      replicas: 1

networks:
  kris-proxy:
    external: true
