version: "3.8"

x-update-config: &update-config
  update_config:
    parallelism: 1
    failure_action: rollback
    order: start-first
    monitor: 120s
    delay: 0s

services:

  nginx:
    image: $IMAGE_RELEASE/nginx:$TAG
    networks:
      - kris-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        # Traefik v1 compatible labels
        - "traefik.docker.network=kris-proxy"
        - "traefik.frontend.entryPoints=http,https"
        - "traefik.frontend.rule=Host:$HOST_NAME"
        - "traefik.port=80"
        # Traefik v2 compatible labels
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.browserXssFilter=true"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.contentTypeNosniff=true"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.customFrameOptionsValue=SAMEORIGIN"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.referrerPolicy=strict-origin-when-cross-origin"
        - "traefik.http.middlewares.${STACK_NAME}-security.headers.stsSeconds=31536000"
        - "traefik.http.routers.${STACK_NAME}-http.entrypoints=http"
        - "traefik.http.routers.${STACK_NAME}-http.middlewares=enforce-https@file,${STACK_NAME}-security"
        - "traefik.http.routers.${STACK_NAME}-http.rule=Host(`${HOST_NAME}`)"
        - "traefik.http.routers.${STACK_NAME}-https.entrypoints=https"
        - "traefik.http.routers.${STACK_NAME}-https.middlewares=${STACK_NAME}-security"
        - "traefik.http.routers.${STACK_NAME}-https.rule=Host(`${HOST_NAME}`)"
        - "traefik.http.routers.${STACK_NAME}-https.tls.certresolver=tlsChallenge"
        - "traefik.http.routers.${STACK_NAME}-https.tls.options=modern@file"
        - "traefik.http.services.${STACK_NAME}.loadbalancer.server.port=80"
      <<: *update-config
      replicas: 1

networks:
  kris-proxy:
    external: true